name: PlayerHide
version: '${version}'
main: tech.shiftmc.playerhide.PlayerHide
api-version: "1.16"
author: Sadness
commands:
  performance:
    description: "The performance level of the player."
    usage: "/playerhide <level>"
    permission: "playerhide.use"
    aliases: []
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.0
  - org.jetbrains.kotlin:kotlin-reflect:1.9.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.12.1
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.12.1
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.2